import { File, Paths } from 'expo-file-system';
import { createContext, ReactNode, useCallback, useContext, useMemo, useState } from 'react';

import { parseSugarwodCsv, WrongFileError } from '@/lib/parse-sugarwod';
import { SUGARWOD_EXPORT_FILENAME } from '@/lib/sugarwod-export';
import {
  buildWorkoutsByDate,
  computeStats,
  MonthSection,
  Stats,
  Workout,
  groupByMonth,
} from '@/lib/workouts';

// Both JSON modules are generated by scripts/convert-workouts.ts.
//
// The __DEV__ guard below is a privacy boundary, not a convenience: Metro
// drops requires inside dead __DEV__ branches from the production dependency
// graph, so the personal "test mode" dataset never ships in release bundles.
// Release builds start empty and get data via in-app CSV import (or preview
// mode, which uses the committed synthetic sample data).
let bundledWorkouts: Workout[] = [];
if (__DEV__) {
  bundledWorkouts = require('@/data/workouts.json') as Workout[];
}
const previewWorkouts = require('@/data/preview-workouts.json') as Workout[];

export type DataSource = 'bundled' | 'imported' | 'preview';

interface ImportResult {
  ok: boolean;
  /** Number of workouts imported (when ok). */
  count?: number;
  /** Error message (when not ok). */
  error?: string;
  canceled?: boolean;
}

interface WorkoutsContextValue {
  workouts: Workout[];
  workoutById: Map<string, Workout>;
  workoutsByDate: Map<string, Workout[]>;
  monthSections: MonthSection[];
  stats: Stats;
  source: DataSource;
  importedCount: number | null;
  /** True when there is no dataset to show — the app must route to onboarding. */
  needsOnboarding: boolean;
  /** Opens the system file picker and imports a SugarWOD CSV export. */
  importCsv(): Promise<ImportResult>;
  /** Switches back to the bundled dataset (dev-only test mode). */
  useBundled(): void;
  /** Switches to the previously imported dataset, if one exists on device. */
  useImported(): void;
  /** Enters preview mode: synthetic sample data plus a persistent exit banner. */
  enterPreview(): void;
  /** Leaves preview mode, falling back to imported data or onboarding. */
  exitPreview(): void;
  /** Deletes the imported dataset from disk and returns to onboarding. */
  resetImportedData(): void;
}

const WorkoutsContext = createContext<WorkoutsContextValue | null>(null);

const importedDataFile = () => new File(Paths.document, 'imported-workouts.json');
const sourcePrefFile = () => new File(Paths.document, 'data-source.json');

// A multi-year SugarWOD export is a few hundred KB. This just needs to be
// high enough to never clip a real export while rejecting an accidentally
// picked photo/video before reading it entirely into memory as text.
const MAX_IMPORT_FILE_BYTES = 25 * 1024 * 1024;

function readImportedWorkouts(): Workout[] | null {
  try {
    const file = importedDataFile();
    if (!file.exists) return null;
    const parsed = JSON.parse(file.textSync()) as Workout[];
    return parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  }
}

function readSourcePref(): DataSource {
  try {
    const file = sourcePrefFile();
    if (!file.exists) return 'bundled';
    return (JSON.parse(file.textSync()).source as DataSource) ?? 'bundled';
  } catch {
    return 'bundled';
  }
}

function writeSourcePref(source: DataSource) {
  try {
    sourcePrefFile().write(JSON.stringify({ source }));
  } catch {
    // Preference persistence is best-effort; the session state is already set.
  }
}

export function WorkoutsProvider({ children }: { children: ReactNode }) {
  const [imported, setImported] = useState<Workout[] | null>(readImportedWorkouts);
  const [savedSource, setSource] = useState<DataSource>(readSourcePref);
  // The saved preference can point at an import that no longer exists on disk.
  const source: DataSource = savedSource === 'imported' && !imported ? 'bundled' : savedSource;

  const importCsv = useCallback(async (): Promise<ImportResult> => {
    try {
      const picked = await File.pickFileAsync({
        mimeTypes: ['text/csv', 'text/comma-separated-values', 'text/plain'],
      });
      if (picked.canceled) return { ok: false, canceled: true };
      if (picked.result.size > MAX_IMPORT_FILE_BYTES) {
        return { ok: false, error: 'That file is too large to be a SugarWOD export.' };
      }
      const csv = await picked.result.text();
      const parsed = parseSugarwodCsv(csv);
      if (parsed.length === 0) {
        return {
          ok: false,
          error: `No workouts in that file. Make sure you picked the ${SUGARWOD_EXPORT_FILENAME} attachment from SugarWOD’s email.`,
        };
      }
      importedDataFile().write(JSON.stringify(parsed));
      setImported(parsed);
      setSource('imported');
      writeSourcePref('imported');
      return { ok: true, count: parsed.length };
    } catch (e) {
      if (e instanceof WrongFileError) {
        return {
          ok: false,
          error: `That file isn’t a SugarWOD export. Look for the ${SUGARWOD_EXPORT_FILENAME} attachment in the email SugarWOD sent you.`,
        };
      }
      return { ok: false, error: e instanceof Error ? e.message : 'Import failed.' };
    }
  }, []);

  const useBundled = useCallback(() => {
    setSource('bundled');
    writeSourcePref('bundled');
  }, []);

  const useImported = useCallback(() => {
    setSource('imported');
    writeSourcePref('imported');
  }, []);

  const enterPreview = useCallback(() => {
    setSource('preview');
    writeSourcePref('preview');
  }, []);

  const exitPreview = useCallback(() => {
    // Back to imported data if any exists; otherwise 'bundled', which in
    // production is empty and routes to onboarding.
    const next: DataSource = imported ? 'imported' : 'bundled';
    setSource(next);
    writeSourcePref(next);
  }, [imported]);

  const resetImportedData = useCallback(() => {
    try {
      const file = importedDataFile();
      if (file.exists) file.delete();
    } catch {
      // Deletion is best-effort; the in-memory state is cleared regardless.
    }
    setImported(null);
    setSource('bundled');
    writeSourcePref('bundled');
  }, []);

  const workouts =
    source === 'preview'
      ? previewWorkouts
      : source === 'imported' && imported
        ? imported
        : bundledWorkouts;

  const value = useMemo<WorkoutsContextValue>(
    () => ({
      workouts,
      workoutById: new Map(workouts.map((w) => [w.id, w])),
      workoutsByDate: buildWorkoutsByDate(workouts),
      monthSections: groupByMonth(workouts),
      stats: computeStats(workouts),
      source,
      importedCount: imported?.length ?? null,
      needsOnboarding: workouts.length === 0,
      importCsv,
      useBundled,
      useImported,
      enterPreview,
      exitPreview,
      resetImportedData,
    }),
    [
      workouts,
      source,
      imported,
      importCsv,
      useBundled,
      useImported,
      enterPreview,
      exitPreview,
      resetImportedData,
    ],
  );

  return <WorkoutsContext.Provider value={value}>{children}</WorkoutsContext.Provider>;
}

export function useWorkouts(): WorkoutsContextValue {
  const value = useContext(WorkoutsContext);
  if (!value) throw new Error('useWorkouts must be used within WorkoutsProvider');
  return value;
}
