import { File, Paths } from 'expo-file-system';
import { createContext, ReactNode, useCallback, useContext, useMemo, useState } from 'react';

import { WrongFileError } from '@/lib/parse-sugarwod';
import { parseWorkoutsCsv } from '@/lib/parse-workouts-csv';
import { SUGARWOD_EXPORT_FILENAME } from '@/lib/sugarwod-export';
import {
  buildWorkoutsByDate,
  computeStats,
  MonthSection,
  Stats,
  Workout,
  groupByMonth,
} from '@/lib/workouts';

// Both JSON modules are generated by scripts/convert-workouts.ts.
//
// The __DEV__ guard below is a privacy boundary, not a convenience: Metro
// drops requires inside dead __DEV__ branches from the production dependency
// graph, so no dev-only dataset ever ships in release bundles. Release
// builds start empty and get data via in-app CSV import (or preview mode,
// which uses the committed synthetic sample data).
export interface DevDataset {
  id: string;
  label: string;
  file: string;
  count: number;
  workouts: Workout[];
}
let devDatasets: DevDataset[] = [];
if (__DEV__) {
  devDatasets = require('@/data/dev-datasets.json') as DevDataset[];
}
const previewWorkouts = require('@/data/preview-workouts.json') as Workout[];
const EMPTY_WORKOUTS: Workout[] = [];

export type DataSource = 'bundled' | 'imported' | 'preview';

interface ImportResult {
  ok: boolean;
  /** Number of workouts imported (when ok). */
  count?: number;
  /** Error message (when not ok). */
  error?: string;
  canceled?: boolean;
}

interface WorkoutsContextValue {
  workouts: Workout[];
  workoutById: Map<string, Workout>;
  workoutsByDate: Map<string, Workout[]>;
  monthSections: MonthSection[];
  stats: Stats;
  source: DataSource;
  importedCount: number | null;
  /** Every local data/*.csv the dev build can parse (empty in production). */
  devDatasets: DevDataset[];
  /** id of the dev dataset currently backing the bundled source, if any. */
  bundledDatasetId: string | null;
  /** True when there is no dataset to show — the app must route to onboarding. */
  needsOnboarding: boolean;
  /** Opens the system file picker and imports a workout CSV export (SugarWOD or Chalk It Pro). */
  importCsv(): Promise<ImportResult>;
  /** Switches to the bundled dataset (dev-only test mode), optionally selecting one by id. */
  useBundled(datasetId?: string): void;
  /** Switches to the previously imported dataset, if one exists on device. */
  useImported(): void;
  /** Enters preview mode: synthetic sample data plus a persistent exit banner. */
  enterPreview(): void;
  /** Leaves preview mode, falling back to imported data or onboarding. */
  exitPreview(): void;
  /** Deletes the imported dataset from disk and returns to onboarding. */
  resetImportedData(): void;
}

const WorkoutsContext = createContext<WorkoutsContextValue | null>(null);

const importedDataFile = () => new File(Paths.document, 'imported-workouts.json');
const sourcePrefFile = () => new File(Paths.document, 'data-source.json');

// A multi-year SugarWOD export is a few hundred KB. This just needs to be
// high enough to never clip a real export while rejecting an accidentally
// picked photo/video before reading it entirely into memory as text.
const MAX_IMPORT_FILE_BYTES = 25 * 1024 * 1024;

function readImportedWorkouts(): Workout[] | null {
  try {
    const file = importedDataFile();
    if (!file.exists) return null;
    const parsed = JSON.parse(file.textSync()) as Workout[];
    return parsed.length > 0 ? parsed : null;
  } catch {
    return null;
  }
}

interface SourcePref {
  source: DataSource;
  datasetId: string | null;
}

function readSourcePref(): SourcePref {
  try {
    const file = sourcePrefFile();
    if (!file.exists) return { source: 'bundled', datasetId: null };
    const parsed = JSON.parse(file.textSync());
    // Legacy pref files predate datasetId and only have `source`.
    return {
      source: (parsed.source as DataSource) ?? 'bundled',
      datasetId: (parsed.datasetId as string | undefined) ?? null,
    };
  } catch {
    return { source: 'bundled', datasetId: null };
  }
}

function writeSourcePref(pref: SourcePref) {
  try {
    sourcePrefFile().write(JSON.stringify(pref));
  } catch {
    // Preference persistence is best-effort; the session state is already set.
  }
}

export function WorkoutsProvider({ children }: { children: ReactNode }) {
  const [imported, setImported] = useState<Workout[] | null>(readImportedWorkouts);
  // One read of the pref file, two pieces of state off it.
  const [savedPref] = useState(readSourcePref);
  const [savedSource, setSource] = useState<DataSource>(savedPref.source);
  const [savedDatasetId, setDatasetId] = useState<string | null>(savedPref.datasetId);
  // The saved preference can point at an import that no longer exists on disk.
  const source: DataSource = savedSource === 'imported' && !imported ? 'bundled' : savedSource;
  // Resolve the saved dataset id against what's actually available: an exact
  // match, else the first dev dataset, else nothing (production: []).
  const matchedDataset = devDatasets.find((d) => d.id === savedDatasetId) ?? devDatasets[0] ?? null;
  const bundledDatasetId = matchedDataset?.id ?? null;

  const importCsv = useCallback(async (): Promise<ImportResult> => {
    try {
      const picked = await File.pickFileAsync({
        mimeTypes: ['text/csv', 'text/comma-separated-values', 'text/plain'],
      });
      if (picked.canceled) return { ok: false, canceled: true };
      if (picked.result.size > MAX_IMPORT_FILE_BYTES) {
        return { ok: false, error: 'That file is too large to be a workout export.' };
      }
      const csv = await picked.result.text();
      const parsed = parseWorkoutsCsv(csv);
      if (parsed.length === 0) {
        return {
          ok: false,
          error: `No workouts in that file. Make sure you picked your SugarWOD ${SUGARWOD_EXPORT_FILENAME} attachment or your Chalk It Pro export.`,
        };
      }
      importedDataFile().write(JSON.stringify(parsed));
      setImported(parsed);
      setSource('imported');
      writeSourcePref({ source: 'imported', datasetId: savedDatasetId });
      return { ok: true, count: parsed.length };
    } catch (e) {
      if (e instanceof WrongFileError) {
        return {
          ok: false,
          error: `That file isn’t a SugarWOD or Chalk It Pro export. Look for the ${SUGARWOD_EXPORT_FILENAME} attachment in the email SugarWOD sent you, or the CSV Chalk It Pro exported.`,
        };
      }
      return { ok: false, error: e instanceof Error ? e.message : 'Import failed.' };
    }
  }, [savedDatasetId]);

  const useBundled = useCallback(
    (datasetId?: string) => {
      setSource('bundled');
      if (datasetId !== undefined) setDatasetId(datasetId);
      writeSourcePref({ source: 'bundled', datasetId: datasetId ?? savedDatasetId });
    },
    [savedDatasetId],
  );

  const useImported = useCallback(() => {
    setSource('imported');
    writeSourcePref({ source: 'imported', datasetId: savedDatasetId });
  }, [savedDatasetId]);

  const enterPreview = useCallback(() => {
    // Sample data is an onboarding trial, not a mode of the real app: once a
    // user has imported their own history, preview is off-limits (the settings
    // dev row disables itself for the same reason).
    if (imported) return;
    setSource('preview');
    writeSourcePref({ source: 'preview', datasetId: savedDatasetId });
  }, [imported, savedDatasetId]);

  const exitPreview = useCallback(() => {
    // Back to imported data if any exists; otherwise 'bundled', which in
    // production is empty and routes to onboarding.
    const next: DataSource = imported ? 'imported' : 'bundled';
    setSource(next);
    writeSourcePref({ source: next, datasetId: savedDatasetId });
  }, [imported, savedDatasetId]);

  const resetImportedData = useCallback(() => {
    try {
      const file = importedDataFile();
      if (file.exists) file.delete();
    } catch {
      // Deletion is best-effort; the in-memory state is cleared regardless.
    }
    setImported(null);
    setSource('bundled');
    writeSourcePref({ source: 'bundled', datasetId: savedDatasetId });
  }, [savedDatasetId]);

  const workouts =
    source === 'preview'
      ? previewWorkouts
      : source === 'imported' && imported
        ? imported
        : (matchedDataset?.workouts ?? EMPTY_WORKOUTS);

  const value = useMemo<WorkoutsContextValue>(
    () => ({
      workouts,
      workoutById: new Map(workouts.map((w) => [w.id, w])),
      workoutsByDate: buildWorkoutsByDate(workouts),
      monthSections: groupByMonth(workouts),
      stats: computeStats(workouts),
      source,
      importedCount: imported?.length ?? null,
      devDatasets,
      bundledDatasetId,
      needsOnboarding: workouts.length === 0,
      importCsv,
      useBundled,
      useImported,
      enterPreview,
      exitPreview,
      resetImportedData,
    }),
    [
      workouts,
      source,
      imported,
      bundledDatasetId,
      importCsv,
      useBundled,
      useImported,
      enterPreview,
      exitPreview,
      resetImportedData,
    ],
  );

  return <WorkoutsContext.Provider value={value}>{children}</WorkoutsContext.Provider>;
}

export function useWorkouts(): WorkoutsContextValue {
  const value = useContext(WorkoutsContext);
  if (!value) throw new Error('useWorkouts must be used within WorkoutsProvider');
  return value;
}
